
//import '@storybook/addon-console
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
}
//Usuario David
localStorage.setItem("jwt", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZTU1ZmY4MGMtNzliNi00YmJjLTkxOGEtNWI4ZDFjMzIzYmM2Iiwia2V5UmVzZWFyY2hlciI6IlUyRnNkR1ZrWDErdlJBUGQ2RU9wT1RZNTNJOExMZnM5aXlYMG1HaDFYZXNuNnJ3VVM0VW5UUXZxVHlXUXZ1MFZlWUxIVVNjVVV0TTIySzgrNHpKcVpRPT0iLCJuYW1lIjoiRGF2aWQiLCJzdXJuYW1lcyI6IlNoYWlraCBVcmJpbmEiLCJpYXQiOjE2MTEyMTg5MTYsImV4cCI6MTYxMzgxMDkxNn0.mOI10x8yLn9Oa_rmsc2b33kY_q0albphXiBbBDNXcLw");
//Usuario Pedro
//localStorage.setItem("jwt", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZTk1MGNjMDItMjhiYS00ZGQ2LWFiNWItMDk4ZDg2ODY3OWQyIiwia2V5UmVzZWFyY2hlciI6IlUyRnNkR1ZrWDErdlJBUGQ2RU9wT1RZNTNJOExMZnM5aXlYMG1HaDFYZXNuNnJ3VVM0VW5UUXZxVHlXUXZ1MFZlWUxIVVNjVVV0TTIySzgrNHpKcVpRPT0iLCJuYW1lIjoiUGVkcm8iLCJzdXJuYW1lcyI6IlJvZHJpZ3VleiIsImlhdCI6MTYxMTIyNDc4MCwiZXhwIjoxNjEzODE2NzgwfQ.1qhVAPkq5UkzXdk-0eC-kn_TgyIab8QgwfzNnmuDyTY");
localStorage.setItem("type", "researcher");
localStorage.setItem("rawKeyResearcher", "bIAtfDHih2wjx1iGpcL8E-Ip4hqW65_EpkYqTBvaq34");
localStorage.setItem("password", "Cabezadesherwood2");