//PERMISSIONS

export enum PERMISSION {
    MEDICAL_WRITE = "MEDICAL_WRITE",
    MEDICAL_READ = "MEDICAL_READ",
    PERSONAL_ACCESS = "PERSONAL_ACCESS",
    BUSINESS_READ = "BUSINESS_READ",
    BUSINESS_WRITE = "BUSINESS_WRITE",
    SHARE_RESEARCHERS = "SHARE_RESEARCHERS",
    EDIT_SUBMISSIONS = "EDIT_SUBMISSIONS",
    EDIT_INVESTIGATION = "EDIT_INVESTIGATION",
    MAKE_DISCOUNTS = "MAKE_DISCOUNTS",
    MANAGE_PHARMACY_CENTRAL = "MANAGE_PHARMACY_CENTRAL",
    MAKE_PHARMACY_REQUESTS = "MAKE_PHARMACY_REQUESTS",
    UPDATE_PHARMACY_CENTRAL = "UPDATE_PHARMACY_CENTRAL",
    ANALYTICS_DEPARTMENT = "ANALYTICS_DEPARTMENT",
    CREATE_APPOINTMENTS = "CREATE_APPOINTMENTS",
    VISUALIZE_APPOINTMENTS = "VISUALIZE_APPOINTMENTS",
    CANCEL_APPOINTMENTS = "CANCEL_APPOINTMENTS",
}

export const PERMISSIONS_LIST = [PERMISSION.MEDICAL_WRITE, PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS, PERMISSION.BUSINESS_READ, PERMISSION.SHARE_RESEARCHERS, PERMISSION.EDIT_SUBMISSIONS, PERMISSION.MAKE_DISCOUNTS, PERMISSION.MANAGE_PHARMACY_CENTRAL, PERMISSION.MAKE_PHARMACY_REQUESTS, PERMISSION.UPDATE_PHARMACY_CENTRAL, PERMISSION.CREATE_APPOINTMENTS, PERMISSION.CANCEL_APPOINTMENTS, PERMISSION.VISUALIZE_APPOINTMENTS, PERMISSION.ANALYTICS_DEPARTMENT]
//Roles
export const MEDICAL_DIRECTOR = [PERMISSION.MEDICAL_WRITE, PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS, PERMISSION.BUSINESS_READ, PERMISSION.SHARE_RESEARCHERS, PERMISSION.MAKE_DISCOUNTS, PERMISSION.EDIT_SUBMISSIONS, PERMISSION.MANAGE_PHARMACY_CENTRAL, PERMISSION.MAKE_PHARMACY_REQUESTS, PERMISSION.UPDATE_PHARMACY_CENTRAL, PERMISSION.CREATE_APPOINTMENTS, PERMISSION.CANCEL_APPOINTMENTS, PERMISSION.VISUALIZE_APPOINTMENTS];
export const STUDENT = [PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS, PERMISSION.BUSINESS_READ];
export const SHERWOOD_STAFF = [PERMISSION.MEDICAL_WRITE, PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS, PERMISSION.BUSINESS_READ, PERMISSION.BUSINESS_WRITE, PERMISSION.SHARE_RESEARCHERS, PERMISSION.EDIT_SUBMISSIONS, PERMISSION.EDIT_INVESTIGATION, PERMISSION.MANAGE_PHARMACY_CENTRAL, PERMISSION.MAKE_PHARMACY_REQUESTS, PERMISSION.UPDATE_PHARMACY_CENTRAL, PERMISSION.CREATE_APPOINTMENTS, PERMISSION.CANCEL_APPOINTMENTS, PERMISSION.VISUALIZE_APPOINTMENTS];
export const DOCTOR = [PERMISSION.MEDICAL_WRITE, PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS,  PERMISSION.EDIT_SUBMISSIONS, PERMISSION.MANAGE_PHARMACY_CENTRAL, PERMISSION.MAKE_PHARMACY_REQUESTS, PERMISSION.UPDATE_PHARMACY_CENTRAL, PERMISSION.CREATE_APPOINTMENTS, PERMISSION.CANCEL_APPOINTMENTS, PERMISSION.VISUALIZE_APPOINTMENTS];
export const DEPARTMENT_HEAD = [PERMISSION.MEDICAL_WRITE, PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS,  PERMISSION.EDIT_SUBMISSIONS, PERMISSION.ANALYTICS_DEPARTMENT, PERMISSION.MANAGE_PHARMACY_CENTRAL, PERMISSION.MAKE_PHARMACY_REQUESTS, PERMISSION.UPDATE_PHARMACY_CENTRAL, PERMISSION.CREATE_APPOINTMENTS, PERMISSION.CANCEL_APPOINTMENTS, PERMISSION.VISUALIZE_APPOINTMENTS];
export const PRIVATE_DOCTOR = [PERMISSION.MEDICAL_WRITE, PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS, PERMISSION.BUSINESS_READ, PERMISSION.MANAGE_PHARMACY_CENTRAL, PERMISSION.MAKE_PHARMACY_REQUESTS, PERMISSION.UPDATE_PHARMACY_CENTRAL, PERMISSION.CREATE_APPOINTMENTS, PERMISSION.CANCEL_APPOINTMENTS, PERMISSION.VISUALIZE_APPOINTMENTS];
export const BUSINESS_MANAGER = [PERMISSION.MEDICAL_WRITE, PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS, PERMISSION.BUSINESS_READ, PERMISSION.SHARE_RESEARCHERS, PERMISSION.BUSINESS_WRITE];
export const ADMIN = [PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS, PERMISSION.SHARE_RESEARCHERS, PERMISSION.MANAGE_PHARMACY_CENTRAL, PERMISSION.MAKE_PHARMACY_REQUESTS, PERMISSION.UPDATE_PHARMACY_CENTRAL, PERMISSION.CREATE_APPOINTMENTS, PERMISSION.CANCEL_APPOINTMENTS, PERMISSION.VISUALIZE_APPOINTMENTS];
export const NURSE = [PERMISSION.MEDICAL_WRITE, PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS, PERMISSION.MANAGE_PHARMACY_CENTRAL, PERMISSION.MAKE_PHARMACY_REQUESTS, PERMISSION.UPDATE_PHARMACY_CENTRAL, PERMISSION.VISUALIZE_APPOINTMENTS];
export const BUSINESS_ASSISTANT = [PERMISSION.BUSINESS_READ];
export const LAB_MANAGER = [PERMISSION.PERSONAL_ACCESS, PERMISSION.MEDICAL_WRITE, PERMISSION.MEDICAL_READ, PERMISSION.SHARE_RESEARCHERS];
export const LAB_ASSISTANT = [PERMISSION.MEDICAL_READ, PERMISSION.MEDICAL_WRITE];
export const SOCIAL_ASSISTANT = [PERMISSION.MEDICAL_WRITE, PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS, PERMISSION.MAKE_DISCOUNTS, PERMISSION.VISUALIZE_APPOINTMENTS];
export const PHARMACY_MANAGER = [PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS, PERMISSION.MANAGE_PHARMACY_CENTRAL, PERMISSION.UPDATE_PHARMACY_CENTRAL];
export const PHARMACY_ASSISTANT = [PERMISSION.MEDICAL_READ, PERMISSION.PERSONAL_ACCESS, PERMISSION.UPDATE_PHARMACY_CENTRAL];
export const MAJOR = [...DOCTOR, PERMISSION.MAKE_PHARMACY_REQUESTS];
export const PHARMACY_CENTRAL_PERMISSIONS = [PERMISSION.MANAGE_PHARMACY_CENTRAL, PERMISSION.UPDATE_PHARMACY_CENTRAL];
export const PHARMACY_RELATED_PERMISSIONS = [...PHARMACY_CENTRAL_PERMISSIONS, PERMISSION.MAKE_PHARMACY_REQUESTS];
export const USER_ROLES = { "PRIVATE_DOCTOR": PRIVATE_DOCTOR, "NURSE": NURSE, "ADMIN": ADMIN, "STUDENT": STUDENT, "MEDICAL_DIRECTOR": MEDICAL_DIRECTOR, "DOCTOR": DOCTOR, "BUSINESS_MANAGER": BUSINESS_MANAGER, "BUSINESS_ASSISTANT": BUSINESS_ASSISTANT, "LAB_MANAGER": LAB_MANAGER, "LAB_ASSISTANT": LAB_ASSISTANT, "SOCIAL": SOCIAL_ASSISTANT, "PHARMACY_MANAGER": PHARMACY_MANAGER, "PHARMACY_ASSISTANT": PHARMACY_ASSISTANT, "MAJOR": MAJOR, "DEPARTMENT_HEAD" : DEPARTMENT_HEAD };
export const ALL_ROLES = { ...USER_ROLES, "SHERWOOD_STAFF": SHERWOOD_STAFF }